site_name: Palazzo Medici
theme_dir: theme
theme: null
copyright: 'Copyright &copy; 2017 <a href="mailto:dave.a.base@gmail.com">David J. Thomas</a>'
repo_url: https://github.com/thePortus/his4936-starter
repo_name: 'GitHub'
pages:
- Home: 'index.md'
- Historiography: 'history.md'
- Other Investigations: 'otherinvestigations.md'
- Source Analysis: 'source.md'
- Building the Palace: 'buildingthepalace.md'
- Donatello's David: 'david.md'
- First Hand Accounts: 'First Hand Accounts of the Vicini.md'
- A Phenomenological Reading of the David: 'overview.md'
- Conclusions: 'conclusion.md'
- Bibliography: 'bib.md'
- Credits: 'credits.md'
